### ISSUE TITLE
TODO: play sound

### ISSUE THREAD

**Issue by gyxx-xc** [gyxx-xc/pong#12]
OpenChampagne

**Comment by ugnjhjf** [comment]
https://1drv.ms/f/s!An3wL8jLytBXo_tJfSxA80LypTvSKg?e=WUWjvQ

Select 1 as SFX for open Champagne

**Comment by ugnjhjf** [comment]
@gyxx-xc

**Comment by ugnjhjf** [comment]
The 1st SFX is applyed
